apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: cloud-resource-demo
spec:
  version: 1.28.5+ec.4
  roles:
    controller:
      labels:
        plugin.k0sproject.io/wasm-enabled: "true" 
    custom:
      - name: runner
        labels:
          plugin.k0sproject.io/wasm-enabled: "true" 
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
          network:
            calico:
              wireguard: true
  extensions:
    helm:
      repositories:
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
      charts:
      - name: ingress-nginx
        chartname: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
        values: |
          controller:
            service:
              type: NodePort
              nodePorts:
                http: "80"
                https: "443"

