---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: cloud-resources
spec:
  title: Hello, Replicated (WASM Edition)
  icon: https://raw.githubusercontent.com/carlosbaraza/web-assembly-logo/master/dist/logo/web-assembly-logo-128px.png
  statusInformers:
    - deployment/cloud-resources
  ports:
    - serviceName: "cloud-resources"
      servicePort: 3000
      localPort: 8888
      applicationUrl: "http://cloud-resources"
  additionalNamespaces:
    - kube-system
