---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-s3
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  package: {{ .Values.providers.registry }}/{{ .Values.providers.aws.packages.s3 }}:{{ .Values.providers.aws.version }}
  {{- with .Values.providers.packagePullSecrets }}
  packagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.providers.pullPolicy (ne .Values.providers.pullPolicy "") }}
  packagePullPolicy: {{ .Values.providers.pullPolicy }}
  {{- end }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-rds
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  package: {{ .Values.providers.registry }}/{{ .Values.providers.aws.packages.rds }}:{{ .Values.providers.aws.version }}
  {{- with .Values.providers.packagePullSecrets }}
  packagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.providers.pullPolicy (ne .Values.providers.pullPolicy "") }}
  packagePullPolicy: {{ .Values.providers.pullPolicy }}
  {{- end }}
