apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-s3-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
spec: {}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-s3
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  package: {{ .Values.providers.registry }}/{{ .Values.providers.aws.s3.package }}:{{ .Values.providers.aws.version }}
  {{- with .Values.providers.packagePullSecrets }}
  packagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.providers.pullPolicy }}
  packagePullPolicy: {{ .Values.providers.pullPolicy }}
  {{- end }}
  runtimeConfigRef:
    name: {{ include "cloud-providers.fullname" . }}-aws-s3-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-rds-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
spec: {}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ include "cloud-providers.fullname" . }}-aws-rds
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  package: {{ .Values.providers.registry }}/{{ .Values.providers.aws.rds.package }}:{{ .Values.providers.aws.version }}
  {{- with .Values.providers.packagePullSecrets }}
  packagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.providers.pullPolicy }}
  packagePullPolicy: {{ .Values.providers.pullPolicy }}
  {{- end }}
  runtimeConfigRef:
    name: {{ include "cloud-providers.fullname" . }}-aws-rds-config
