apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-9"
type: Opaque
data:
  credentials: {{ .Values.provider.aws.credentials | b64enc }}
