apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Release.Name }}-aws-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }}
      name: aws-creds
      key: credentials
