apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: {{ include "cloud-resources.fullname" . }}-aws-crds
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws-crd:v0.33.0
