{{- if .Values.rds.enabled }}
apiVersion: rds.aws.crossplane.io/v1beta1
kind: DBInstance
metadata:
  name: {{ .Values.rds.instanceName }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    dbInstanceClass: {{ .Values.rds.instanceClass }}
    masterUsername: {{ .Values.rds.masterUsername }}
    allocatedStorage: {{ .Values.rds.allocatedStorage }}
    engine: {{ .Values.rds.engine }}
    engineVersion: {{ .Values.rds.engineVersion }}
    skipFinalSnapshotBeforeDeletion: {{ .Values.rds.skipFinalSnapshot }}
    publiclyAccessible: {{ .Values.rds.publiclyAccessible }}
  providerConfigRef:
    name: {{ .Release.Name }}-aws-provider
{{- end }}
