{{- if .Values.rds.enabled }}
apiVersion: rds.aws.upbound.io/v1beta2
kind: Instance
metadata:
  name: {{ .Values.rds.instanceName }}
  labels: {{ include "cloud-resources.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    instanceClass: {{ .Values.rds.instanceClass }}
    username: {{ .Values.rds.masterUsername }}
    passwordSecretRef:
      key: password
      name: {{ .Values.rds.instanceName }}-master-password
      namespace: {{ .Release.Namespace }}
    allocatedStorage: {{ .Values.rds.allocatedStorage }}
    engine: {{ .Values.rds.engine }}
    engineVersion: "{{ .Values.rds.engineVersion }}"
    publiclyAccessible: {{ .Values.rds.publiclyAccessible }}
    skipFinalSnapshot: false
    finalSnapshotIdentifier: $(metadata.uid)-final-snapshot
  providerConfigRef:
    name: {{ .Release.Name }}-aws-provider
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rds.instanceName }}-master-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.rds.masterUserPassword | b64enc }}
