{{- if .Values.rds.enabled }}
apiVersion: rds.aws.upbound.io/v1beta2
kind: DBInstance
metadata:
  name: {{ .Values.rds.instanceName }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    dbInstanceClass: {{ .Values.rds.instanceClass }}
    masterUsername: {{ .Values.rds.masterUsername }}
    masterUserPasswordSecretRef:
      key: password
      name: {{ .Values.rds.instanceName }}-master-password
      namespace: {{ .Release.Namespace }}
    allocatedStorage: {{ .Values.rds.allocatedStorage }}
    engine: {{ .Values.rds.engine }}
    engineVersion: "{{ .Values.rds.engineVersion }}"
    skipFinalSnapshotBeforeDeletion: {{ .Values.rds.skipFinalSnapshot }}
    publiclyAccessible: {{ .Values.rds.publiclyAccessible }}
  providerConfigRef:
    name: {{ .Release.Name }}-aws-provider
    apiVersion: aws.upbound.io/v1beta1
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rds.instanceName }}-master-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.rds.masterUserPassword | b64enc }}
