{{- if .Values.s3.enabled }}
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.s3.bucketName }}
spec:
  forProvider:
    region: {{ .Values.aws.region }}
    acl: private
    locationConstraint: {{ .Values.aws.region }}
    {{- if .Values.s3.versioning }}
    versioning: true
    {{- end }}
    {{- if .Values.s3.encryption }}
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    {{- end }}
  providerConfigRef:
    name: {{ .Release.Name }}-aws-provider
{{- end }}
